_target_: atria_datasets.pipelines.atria_data_pipeline.AtriaDataPipeline
_partial_: false
defaults:
- _self_
- /dataset@dataset: null
- /batch_sampler@batch_samplers.train: null
- /batch_sampler@batch_samplers.evaluation: null
dataset: ???
data_dir: null
preprocess_transforms:
  _target_: atria_core.transforms.base.DataTransformsDict
  train: null
  evaluation: null
runtime_transforms:
  _target_: atria_core.transforms.base.DataTransformsDict
  train: null
  evaluation: null
allowed_keys: null
batch_samplers:
  _target_: atria_datasets.core.batch_samplers.batch_samplers_dict.BatchSamplersDict
  train: null
  evaluation: null
train_dataloader:
  _target_: atria_datasets.pipelines.utilities.auto_dataloader
  _partial_: true
  batch_size: 64
  num_workers: 4
  pin_memory: true
  drop_last: false
evaluation_dataloader:
  _target_: atria_datasets.pipelines.utilities.auto_dataloader
  _partial_: true
  batch_size: 64
  num_workers: 4
  pin_memory: true
  drop_last: false
use_validation_set_for_test: false
use_train_set_for_test: false
tar_sampling_chunk_size: 1000
enable_sharded_storage: false
shard_storage_type: WEBDATASET
num_processes: 8
max_shard_size: 100000
max_memory_per_actor: 524288000
max_concurrent_tasks_limit: 100
streaming_mode: false
dataset_splitting_enabled: false
split_ratio: 0.9
access_token: null
overwrite_existing_cached: false
overwrite_existing_shards: false
collate_fn: default_collate
