_target_: atria_ml.training.engines.evaluation.TestEngine
_partial_: false
epoch_length: null
outputs_to_running_avg: null
logging:
  _target_: atria_ml.training.configs.logging_config.LoggingConfig
  logging_steps: 100
  refresh_rate: 10
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metric_factory: null
metric_logging_prefix: null
test_run: false
use_fixed_batch_iterator: false
checkpoints_dir: checkpoints
test_checkpoint_file: null
save_model_outputs_to_disk: false
checkpoint_types: null
with_amp: false
