_target_: atria_ml.training.engines.evaluation.VisualizationEngine
_partial_: false
epoch_length: 1
outputs_to_running_avg: null
logging:
  _target_: atria_ml.training.configs.logging_config.LoggingConfig
  logging_steps: 100
  refresh_rate: 10
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metric_factory: null
metric_logging_prefix: null
test_run: false
use_fixed_batch_iterator: false
checkpoints_dir: checkpoints
visualize_every_n_epochs: 1
visualize_on_start: false
use_ema_for_visualize: false
with_amp: false
