_target_: atria_ml.training.engines.evaluation.InferenceEngine
epoch_length: null
outputs_to_running_avg: null
logging:
  _target_: atria_ml.training.configs.logging_config.LoggingConfig
  logging_steps: 100
  refresh_rate: 10
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metric_logging_prefix: null
test_run: false
use_fixed_batch_iterator: false
with_amp: false
