# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._trainer.Trainer
_zen_partial: false
_zen_exclude:
- n_devices
- backend
- experiment_name
defaults:
- /engine@training_engine: default_training_engine
- /engine@validation_engine: default_validation_engine
- /engine@test_engine: default_test_engine
- /engine@visualization_engine: default_visualization_engine
- /data_pipeline@data_pipeline: default
- /model_pipeline@model_pipeline: layout_token_classification
- override /optimizer@training_engine.optimizer: adamw
- override /lr_scheduler@training_engine.lr_scheduler: cosine_annealing_lr
- _self_
output_dir: outputs/trainer/layout_entity_recognition/${resolve_experiment_name:${experiment_name}}/
seed: 42
deterministic: false
do_train: true
do_validation: true
do_visualization: false
do_test: true
vis_batch_size: 64
test_run: false
n_devices: 1
backend: nccl
experiment_name: _to_be_resolved_
