# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._trainer.Trainer
_zen_partial: false
_zen_exclude:
- n_devices
- backend
- experiment_name
defaults:
- /data_pipeline@data_pipeline: default
- /model_pipeline@model_pipeline: object_detection
- /metric_factory@metric_factory.cocoeval: cocoeval
- /engine@training_engine: default_training_engine
- /engine@validation_engine: default_validation_engine
- /engine@test_engine: default_test_engine
- /engine@visualization_engine: default_visualization_engine
- /data_transform@data_pipeline.runtime_transforms.train: document_instance_mmdet_transform/train
- /data_transform@data_pipeline.runtime_transforms.evaluation: document_instance_mmdet_transform/evaluation
- override /optimizer_factory@training_engine.optimizer_factory: sgd
- override /lr_scheduler_factory@training_engine.lr_scheduler_factory: multi_step_lr
- _self_
model_pipeline: ???
test_engine: ???
metric_factory: ???
task_type: layout_analysis
data_pipeline:
  allowed_keys:
  - index
  - sample_id
  - page_id
  - total_num_pages
  - gt
  - image
  collate_fn: mmdet_pseudo_collate
training_engine:
  model_checkpoint_config:
    monitored_metric: null
  optimizer_factory:
    lr: 0.02
    weight_decay: 0.0001
    momentum: 0.9
  lr_scheduler_factory:
    milestones:
    - 16
    - 22
    gamma: 0.1
  warmup_config:
    warmup_ratio: 0.0
    warmup_steps: 500
validation_engine:
  validate_every_n_epochs: 10
  validate_on_start: false
visualization_engine:
  visualize_every_n_epochs: 10
  visualize_on_start: false
output_dir: outputs/trainer/layout_analysis/${data_pipeline.dataset.dataset_name}/${model_pipeline.model.name}/${experiment_name}
seed: 42
deterministic: false
do_train: true
do_validation: true
do_visualization: true
do_test: true
vis_batch_size: 64
n_devices: 1
backend: nccl
experiment_name: ???
