# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._trainer.Trainer
_zen_partial: false
_zen_exclude:
- n_devices
- backend
- experiment_name
defaults:
- /data_pipeline@data_pipeline: default
- /model_pipeline@model_pipeline: question_answering
- /engine@training_engine: default_training_engine
- /engine@validation_engine: default_validation_engine
- /engine@test_engine: default_test_engine
- /engine@visualization_engine: default_visualization_engine
- _self_
data_pipeline: ???
model_pipeline: ???
training_engine: ???
validation_engine: ???
visualization_engine: ???
test_engine: ???
output_dir: outputs/trainer/visual_question_answering/${resolve_experiment_name:${experiment_name}}/
seed: 42
deterministic: false
do_train: true
do_validation: true
do_visualization: false
do_test: true
vis_batch_size: 64
n_devices: 1
backend: nccl
experiment_name: ''
