_partial_: false
lr: 1.0
rho: 0.9
eps: 1.0e-06
weight_decay: 0
foreach: null
maximize: false
differentiable: false
module: torch.optim.adadelta.Adadelta
_target_: atria_ml.registry.registry_groups.OptimizerBuilder
