_partial_: false
lr: 0.01
lr_decay: 0
weight_decay: 0
initial_accumulator_value: 0
eps: 1.0e-10
foreach: null
maximize: false
differentiable: false
module: torch.optim.adagrad.Adagrad
_target_: atria_ml.registry.registry_groups.OptimizerBuilder
