_target_: atria_ml.registry.registry_groups.OptimizerConfig
optimizer: torch.optim.Adamax
lr: 0.002
betas:
- 0.9
- 0.999
eps: 1.0e-08
weight_decay: 0
foreach: null
maximize: false
differentiable: false
