_target_: atria_ml.registry.registry_groups.OptimizerConfig
optimizer: torch.optim.ASGD
lr: 0.01
lambd: 0.0001
alpha: 0.75
t0: 1000000.0
weight_decay: 0
foreach: null
maximize: false
differentiable: false
