_target_: atria_ml.registry.registry_groups.OptimizerConfig
optimizer: torch.optim.LBFGS
lr: 1
max_iter: 20
max_eval: null
tolerance_grad: 1.0e-07
tolerance_change: 1.0e-09
history_size: 100
line_search_fn: null
