_partial_: false
lr: 0.01
alpha: 0.99
eps: 1.0e-08
weight_decay: 0
momentum: 0
centered: false
foreach: null
maximize: false
differentiable: false
module: torch.optim.rmsprop.RMSprop
_target_: atria_ml.registry.registry_groups.OptimizerBuilder
