_partial_: false
lr: 0.01
etas:
- 0.5
- 1.2
step_sizes:
- 1.0e-06
- 50
foreach: null
maximize: false
differentiable: false
module: torch.optim.rprop.Rprop
_target_: atria_ml.registry.registry_groups.OptimizerBuilder
