_partial_: false
lr: ???
momentum: 0
dampening: 0
weight_decay: 0
nesterov: false
maximize: false
foreach: null
differentiable: false
module: torch.optim.sgd.SGD
_target_: atria_ml.registry.registry_groups.OptimizerBuilder
