_target_: atria_ml.registry.registry_groups.OptimizerConfig
optimizer: torch.optim.SGD
lr: ???
momentum: 0
dampening: 0
weight_decay: 0
nesterov: false
maximize: false
foreach: null
differentiable: false
