# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._inferencer.Inferencer
_zen_partial: false
_zen_exclude:
- hydra
- n_devices
- backend
defaults:
- /model_pipeline@model_pipeline: object_detection
- /metric_factory@metric_factory.cocoeval: cocoeval
- /engine@inference_engine: default_inference_engine
- /data_transform@runtime_transforms: document_instance_mmdet_transform/evaluation
- _self_
model_pipeline: ???
inference_engine: ???
task_type: layout_analysis
evaluation_dataloader:
  _target_: atria_datasets.pipelines.utilities.auto_dataloader
  _partial_: true
  batch_size: 64
  num_workers: 4
  pin_memory: true
  drop_last: false
allowed_keys:
- id
- index
- doc_id
- image
- ground_truth
collate_fn: mmdet_pseudo_collate
hydra:
  run:
    dir: outputs/evaluator/${dataset.name}/${model_pipeline.model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: hydra
  job:
    chdir: false
  searchpath:
  - pkg://atria/conf
  - pkg://atria_examples/conf
n_devices: 1
backend: nccl
