# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._inferencer.Inferencer
_zen_partial: false
_zen_exclude:
- hydra
- n_devices
- backend
defaults:
- /metric_factory@metric_factory.sequence_anls: sequence_anls
- /engine@inference_engine: default_inference_engine
- _self_
inference_engine: ???
task_type: visual_question_answering
evaluation_dataloader:
  _target_: atria_datasets.pipelines.utilities.auto_dataloader
  _partial_: true
  batch_size: 64
  num_workers: 0
  pin_memory: true
  drop_last: false
allowed_keys: null
collate_fn: default_collate
hydra:
  run:
    dir: outputs/inferencer/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: hydra
  job:
    chdir: false
  searchpath:
  - pkg://atria/conf
  - pkg://atria_examples/conf
n_devices: 1
backend: nccl
