_target_: atria_metrics.qa.anls.ANLS
_partial_: true
threshold: 0.5
output_transform:
  path: atria_metrics.qa.output_transforms._anls_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
