_target_: atria_metrics.detection.cocoeval.COCOEvalMetric
_partial_: true
output_transform:
  path: atria_metrics.detection.output_transforms._cocoeval_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
