_target_: atria_ml.training.metrics.instance_classification.f1_score.f1_score
_partial_: true
output_transform:
  path: atria_ml.training.metrics.instance_classification.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
