_target_: atria_ml.training.metrics.layout.recall.LayoutRecall
_partial_: true
output_transform:
  path: atria_ml.training.metrics.layout.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
average: false
is_multilabel: false
device: cpu
