_target_: atria_metrics.qa.sequence_anls.sequence_anls
_partial_: true
output_transform:
  path: atria_metrics.qa.output_transforms._sequence_anls_output_transform
  _target_: hydra_zen.funcs.get_obj
threshold: 0.5
