# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria_ml.task_pipelines._evaluator.Evaluator
_zen_partial: false
_zen_exclude:
- hydra
defaults:
- _self_
- /data_pipeline@data_pipeline: default
- /model_pipeline@model_pipeline: image_classification
- /engine@test_engine: default_test_engine
data_pipeline: ???
model_pipeline: ???
test_engine: ???
run_dir: ???
seed: 42
deterministic: false
backend: nccl
n_devices: 1
hydra:
  run:
    dir: ${checkpoint_dir}
  output_subdir: hydra
  job:
    chdir: false
  searchpath:
  - pkg://atria/conf
  - pkg://atria_examples/conf
