_target_: atria_datasets.image_classification.cifar10.Cifar10
_partial_: false
dataset_name: cifar10
config_name: main
data_urls: null
max_train_samples: null
max_validation_samples: null
max_test_samples: null
