_partial_: false
metric_name: ???
trainer: null
save_history: false
param_group_index: null
module: ignite.handlers.param_scheduler.ReduceLROnPlateauScheduler
_target_: atria_ml.registry.registry_groups.LRSchedulerBuilder
