_target_: atria_ml.registry.registry_groups.SchedulerConfig
scheduler: ignite.handlers.ReduceLROnPlateauScheduler
metric_name: ???
trainer: null
save_history: false
param_group_index: null
scheduler_kwargs: ???
